name: Docker Build
on: [push, pull_request]

jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f Dockerfile_ubuntu
